root: ./

​structure:
  readme: README.md
  summary: SUMMARY.md​

redirects:
 gravitee-essentials/gravitee-core-concepts: gravitee-platform/gravitee-core-concepts.md
 gravitee-essentials/gravitee-offerings-ce-vs-ee#enterprise-version-of-gravitee-cockpit: gravitee-platform/gravitee-offerings-ce-vs-ee/README.md
 gravitee-essentials/gravitee-offerings-ce-vs-ee: gravitee-platform/gravitee-offerings-ce-vs-ee/README.md

