root: ./

​structure:
  readme: README.md
  summary: SUMMARY.md​

redirects:
 getting-started/configuration/configure-alerts-and-notifications: getting-started/configuration/notifications.md
 guides/api-configuration/v4-api-configuration/documentation: configure-v4-apis/documentation.md
 installation-and-upgrades/repositories: configure-apim/repositories/README.md
 installation-and-upgrades/repositories/mongodb: configure-apim/repositories/mongodb.md
 reference/policy-reference/message-filtering: policies/message-filtering.md
 installation-and-upgrades/repositories/elasticsearch: configure-apim/repositories/elasticsearch.md
 installation-and-upgrades/repositories/redis: configure-apim/repositories/redis.md
 installation-and-upgrades/repositories/jdbc: configure-apim/repositories/jdbc.md
 installation-and-upgrades/advanced-hybrid-deployment: hybrid-deployment/overview.md
 guides/developer-portal/tools-and-features: developer-portal/configuration-file.md
 installation-and-upgrades/upgrading-gravitee-api-management: install-and-upgrade/upgrade-guide.md
 overview/gravitee-apim-enterprise-edition/enterprise-support: overview/enterprise-edition.md
 using-the-product/managing-your-apis/resources: policies/resources.md
 using-the-product/managing-your-apis/preparing-apis-for-subscribers/plans/mtls: expose-apis/plans/mtls.md
 using-the-product/managing-your-apis/policy-studio/policies-for-your-apis/d-h/data-logging-masking: policies/data-logging-masking.md
 most-common-use-cases/adding-role-based-access-control-to-your-jwt-plan: getting-started/use-case-tutorials/add-rbac-to-your-jwt-plan.md
 using-the-product/using-the-gravitee-api-management-components/general-configuration/secret-providers: configure-apim/sensitive-data-management/README.md
 using-the-product/managing-your-apis/resources: policies/resources.md
 using-the-product/managing-your-apis/policy-studio/policies-for-your-apis/d-h/dynamic-routing: policies/dynamic-routing.md
 using-the-product/managing-your-apis/api-configuration/v2-api-configuration/documentation: configure-v2-apis/documentation.md
 using-the-product/managing-your-apis/preparing-apis-for-subscribers/plans: expose-apis/plans.md

