root: ./

​structure:
  readme: README.md
  summary: SUMMARY.md​

redirects:
 getting-started/configuration/configure-alerts-and-notifications: getting-started/configuration/notifications.md
 guides/api-configuration/v4-api-configuration/documentation: configure-v4-apis/documentation.md
 installation-and-upgrades/repositories: configure-apim/repositories/README.md
 installation-and-upgrades/repositories/mongodb: configure-apim/repositories/mongodb.md
 reference/policy-reference/message-filtering: policies/message-filtering.md
 installation-and-upgrades/repositories/elasticsearch: configure-apim/repositories/elasticsearch.md
 installation-and-upgrades/repositories/redis: configure-apim/repositories/redis.md
 installation-and-upgrades/repositories/jdbc: configure-apim/repositories/jdbc.md
 installation-and-upgrades/advanced-hybrid-deployment: hybrid-deployment/overview.md
 guides/developer-portal/tools-and-features: developer-portal/configuration-file.md
 installation-and-upgrades/upgrading-gravitee-api-management: install-and-upgrade/upgrade-guide.md
 overview/gravitee-apim-enterprise-edition/enterprise-support: overview/enterprise-edition.md
 using-the-product/managing-your-apis/resources: policies/resources.md
 using-the-product/managing-your-apis/preparing-apis-for-subscribers/plans/mtls: expose-apis/plans/mtls.md
 using-the-product/managing-your-apis/policy-studio/policies-for-your-apis/d-h/data-logging-masking: policies/data-logging-masking.md
 most-common-use-cases/adding-role-based-access-control-to-your-jwt-plan: getting-started/use-case-tutorials/add-rbac-to-your-jwt-plan.md
 using-the-product/using-the-gravitee-api-management-components/general-configuration/secret-providers: configure-apim/sensitive-data-management/README.md
 installation-and-upgrades/repositories/cache: configure-apim/cache.md
 using-the-product/managing-your-apis/api-configuration/v4-api-configuration/endpoints: configure-v4-apis/endpoints/README.md
 using-the-product/managing-your-apis/create-apis/v2-apis-and-v4-apis-comparison: create-apis/v2-and-v4-api-comparison.md
 overview/apim-architecture: overview/architecture.md
 using-the-product/managing-your-apis/api-configuration/v4-api-configuration/endpoints/health-check: configure-v4-apis/health-checks.md
 using-the-product/managing-your-apis/api-configuration/v4-api-configuration/entrypoints/cors: configure-v4-apis/cors.md
 releases-and-changelog/release-notes: overview/release-notes/README.md
 using-the-product/managing-your-apis/create-apis/openapi-spec-import: create-apis/import-apis.md
 using-the-product/using-the-gravitee-api-management-components/developer-portal/publishing-and-managing-apis-with-the-gravitee-developer-portal/documentation: developer-portal/api-documentation.md
 guides/gravitee-expression-language: getting-started/gravitee-expression-language.md
 using-the-product/using-the-gravitee-api-management-components/developer-portal/configuring-and-customizing-the-gravitee-developer-portal/layout-and-theme-customization: developer-portal/layout-and-theme.md
 using-the-product/managing-your-apis/api-configuration/v2-api-configuration/general-proxy-settings: configure-v2-apis/proxy-settings.md
 using-the-product/federating-your-apis/3rd-party-providers/solace: federation/3rd-party-providers/solace.md
 using-the-product/managing-your-apis/api-configuration/v4-api-configuration/entrypoints/entrypoint-reference/webhook: configure-v4-apis/entrypoints/webhook.md
 using-the-product/managing-your-apis/policy-studio/v2-api-policy-studio: policies/v2-api-policy-studio.md
 using-the-product/managing-your-apis/preparing-apis-for-subscribers/plans/mtls/mtls-plans-overview: expose-apis/plans/mtls.md
 using-the-product/managing-your-apis/api-configuration/v4-api-configuration: configure-v4-apis/general-settings.md
 overview/plugins-and-api-definitions/gravitee-api-definitions-and-execution-engines: overview/execution-engine.md
 using-the-product/managing-your-apis/api-configuration/v4-api-configuration/version-history: configure-v4-apis/version-history.md
 using-the-product/managing-your-apis/policy-studio/policy-reference: policies/policy-reference.md
 using-the-product/managing-your-apis/create-apis: create-apis/overview.md
 getting-started/tutorials: getting-started/use-case-tutorials/README.md
 using-the-product/using-the-gravitee-api-management-components/developer-portal/webhook-subscription-management: developer-portal/webhook-subscriptions.md
 getting-started/install-gravitee-api-management/installing-a-gravitee-gateway-with-a-hybrid-deployment/advanced-hybrid-deployment: hybrid-deployment/overview.md
 using-the-product/managing-your-apis/api-configuration/v4-api-configuration/endpoints/v4-proxy-api-endpoints: configure-v4-apis/endpoints/README.md
 using-the-product/using-the-gravitee-api-management-components/developer-portal/configuring-and-customizing-the-gravitee-developer-portal/general-settings: developer-portal/settings.md
 using-the-product/managing-your-apis/preparing-apis-for-subscribers/subscriptions: expose-apis/subscriptions.md 
 installation-and-upgrades/advanced-hybrid-deployment/gateway-and-bridge-compatibility-versions: hybrid-deployment/overview.md
 using-the-product/using-the-gravitee-api-management-components/apim-console/configuring-notifications-and-alerts-for-your-apis: gravitee-gateway/alerts.md
 using-the-product/managing-your-apis/api-configuration/v4-api-configuration/entrypoints/entrypoint-reference/server-sent-events: configure-v4-apis/entrypoints/server-sent-events.md
 using-the-product/managing-your-apis/api-configuration/v4-api-configuration/entrypoints/v4-message-api-entrypoints/websocket: configure-v4-apis/entrypoints/websocket.md
 getting-started/install-and-upgrade-guides/install-on-kubernetes: install-and-upgrade/kubernetes.md
 using-the-product/using-the-gravitee-api-management-components/developer-portal: developer-portal/configuration-file.md
 using-the-product/managing-your-apis/create-apis/the-api-creation-wizard: create-apis/v4-api-creation-wizard.md
 using-the-product/managing-your-apis/api-measurement-tracking-and-analytics/audit-trail: api-analytics/audit-trail.md
 using-the-product/managing-your-apis/api-configuration/v4-api-configuration/audit-logs: configure-v4-apis/audit-logs.md
 guides/developer-portal/tools-and-features/documentation: developer-portal/api-documentation.md
 guides/policy-design/v2-api-policy-design-studio: policies/v2-api-policy-studio.md
 using-the-product/managing-your-apis/api-configuration/v4-api-configuration/entrypoints/v4-message-api-entrypoints/webhook: configure-v4-apis/entrypoints/webhook.md
 using-the-product/managing-your-apis/policy-studio: policies/v4-api-policy-studio.md
 using-the-product/managing-your-apis/create-apis/creating-and-publishing-an-api-with-the-management-api: getting-started/use-case-tutorials/create-and-publish-an-api-using-the-management-api.md
 using-the-product/administration: administration/organizations-and-environments.md
 overview/changelog/apim-4.5.x: overview/changelog/README.md
 releases-and-changelog/release-notes/apim-4.4: overview/release-notes/README.md
 guides/developer-portal/tools-and-features: developer-portal/settings.md
 getting-started/install-guides/install-on-docker/: install-and-upgrade/docker/README.md

